"""make

Revision ID: 47acd1e9c2f9
Revises: b4a722baad96
Create Date: 2025-06-13 06:37:26.043670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '47acd1e9c2f9'
down_revision: Union[str, None] = 'b4a722baad96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runs', 'hazard_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runs', 'hazard_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ### 