"""Add Building model for storing individual buildings

Revision ID: 683f86738c18
Revises: f680a4c7fc49
Create Date: 2025-06-02 05:23:21.383897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '683f86738c18'
down_revision: Union[str, None] = 'f680a4c7fc49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('guid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('asset_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['building_datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_guid'), 'buildings', ['guid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buildings_guid'), table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###
