"""add_eal_fields_to_run

Revision ID: 685ea8ef98ca
Revises: 683f86738c18
Create Date: 2025-06-02 06:16:07.921706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '685ea8ef98ca'
down_revision: Union[str, None] = '683f86738c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('total_eal', sa.Float(), nullable=True))
    op.add_column('runs', sa.Column('buildings_analyzed', sa.Integer(), nullable=True))
    op.add_column('runs', sa.Column('buildings_with_values', sa.Integer(), nullable=True))
    op.add_column('runs', sa.Column('total_asset_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'total_asset_value')
    op.drop_column('runs', 'buildings_with_values')
    op.drop_column('runs', 'buildings_analyzed')
    op.drop_column('runs', 'total_eal')
    # ### end Alembic commands ### 
