"""add

Revision ID: 9421ecadaa9b
Revises: d00ddf7e7f5d
Create Date: 2025-06-13 05:43:56.935297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9421ecadaa9b'
down_revision: Union[str, None] = 'd00ddf7e7f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modified_hazards', sa.Column('model_results', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modified_hazards', 'model_results')
    # ### end Alembic commands ### 