"""add

Revision ID: d00ddf7e7f5d
Revises: 685ea8ef98ca
Create Date: 2025-06-13 01:12:57.982173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd00ddf7e7f5d'
down_revision: Union[str, None] = '685ea8ef98ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hazard_interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('hazard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hazard_id'], ['hazards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hazard_interventions_name'), 'hazard_interventions', ['name'], unique=False)
    op.create_table('modified_hazards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_hazard_id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.Column('wse_raster_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_output_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['intervention_id'], ['hazard_interventions.id'], ),
    sa.ForeignKeyConstraint(['original_hazard_id'], ['hazards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('runs', sa.Column('modified_hazard_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'runs', 'modified_hazards', ['modified_hazard_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_column('runs', 'modified_hazard_id')
    op.drop_table('modified_hazards')
    op.drop_index(op.f('ix_hazard_interventions_name'), table_name='hazard_interventions')
    op.drop_table('hazard_interventions')
    # ### end Alembic commands ### 